In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()

arr1=np.array([2,4,6])
arr1
# Create a 2-dimensional NumPy array using np.array()
arr2=np.array([[2,4,6],[4,6,7]])
arr2
# Create a 3-dimensional Numpy array using np.array()
arr3=np.array([[[1,2,3],[2,3,4]],[[4,5,6],[6,7,8]],[[6,7,9],[3,6,8]]])
arr3

array([[[1, 2, 3],
        [2, 3, 4]],

       [[4, 5, 6],
        [6, 7, 8]],

       [[6, 7, 9],
        [3, 6, 8]]])

In [13]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
arr1.shape
arr1.ndim
type(arr1)
arr1.size
arr1.dtype

dtype('int64')

In [17]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
arr1_pd=pd.DataFrame(arr1)
arr1_pd

0
0  2
1  4
2  6

In [19]:
# Create an array of shape (10, 2) with only ones
arr_ones=np.ones((10,2))
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# Create an array of shape (7, 2, 3) of only zeros
arr_zeros=np.zeros((7,2,3))
arr_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Create an array within a range of 0 and 100 with step 3

In [42]:
arr_random=np.arange(0,100,3)
arr_random

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [22]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_random=np.random.randint(1,100,size=(7,2))
arr_random

array([[29, 58],
       [78, 47],
       [46, 92],
       [ 8, 75],
       [78, 19],
       [81, 18],
       [88, 63]])

In [43]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_random_float=np.random.random((3,5))
arr_random_float

array([[0.24102547, 0.68326352, 0.60999666, 0.83319491, 0.17336465],
       [0.39106061, 0.18223609, 0.75536141, 0.42515587, 0.20794166],
       [0.56770033, 0.03131329, 0.84228477, 0.44975413, 0.39515024]])

In [32]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_random=np.random.randint(0,10,size=(4,6))
arr_random

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [44]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
variable=np.random.randint(0,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(variable)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [36]:
# Find the 0'th index of the latest array you created
variable[0][0]

8

In [37]:
# Get the first 2 rows of latest array you created
variable[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [39]:
# Get the first 2 values of the first 2 rows of the latest array
variable[:2,:2]

array([[8, 0],
       [2, 4]])

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

In [49]:
arr5=np.random.randint(1,10,size=(3,5))
ones=np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
# Add the two arrays together
arr5+ones

array([[10.,  6.,  2.,  4.,  9.],
       [ 7.,  9., 10.,  5.,  2.],
       [ 2.,  5.,  8.,  3.,  4.]])

In [51]:
# Create another array of ones of shape (5, 3)
ones2=np.ones((5,3))
ones2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
arr5.T+ones2

array([[10.,  7.,  2.],
       [ 6.,  9.,  5.],
       [ 2., 10.,  8.],
       [ 4.,  5.,  3.],
       [ 9.,  2.,  4.]])

In [57]:
# Create another array of ones of shape (3, 5)
ones3=np.ones((3,5))

In [ ]:
# Subtract the new array of ones from the other most recent array

In [58]:
ones3-ones2.T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
# Multiply the ones array with the latest array
ones3*ones2.T

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
# Take the latest array to the power of 2 using '**'
ones3**2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
# Do the same thing with np.square()
np.square(ones3)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
# Find the mean of the latest array using np.mean()
np.mean(arr3)

5.0

In [63]:
# Find the maximum of the latest array using np.max()
np.max(arr3)

9

In [64]:
# Find the minimum of the latest array using np.min()
np.min(arr3)

1

In [65]:
# Find the standard deviation of the latest array
np.std(arr3)

2.2852182001336816

In [66]:
# Find the variance of the latest array
np.var(arr3)

5.222222222222222

In [69]:
# Reshape the latest array to (3, 5, 1)
arr3.reshape(3,3,2)

array([[[1, 2],
        [3, 2],
        [3, 4]],

       [[4, 5],
        [6, 6],
        [7, 8]],

       [[6, 7],
        [9, 3],
        [6, 8]]])

In [70]:
# Transpose the latest array
arr3.T

array([[[1, 4, 6],
        [2, 6, 3]],

       [[2, 5, 7],
        [3, 7, 6]],

       [[3, 6, 9],
        [4, 8, 8]]])

In [71]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr6=np.random.randint(1,10,size=(3,3))
arr7=np.random.randint(1,10,size=(3,2))

In [84]:
# Perform a dot product on the two newest arrays you created
np.dot(arr6,arr7)

array([[15, 12],
       [60, 43],
       [34, 24]])

In [75]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr8=np.random.randint(0,10,size=(4,3))
arr9=np.random.randint(0,10,size=(4,3))

In [86]:
# Perform a dot product on the two newest arrays you created
np.dot(arr8.T, arr9)

array([[ 39,  86,  45],
       [ 81, 122, 101],
       [ 84, 130,  68]])

array([[ 39,  86,  45],
       [ 81, 122, 101],
       [ 84, 130,  68]])

In [87]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(arr8.T, arr9)

array([[ 39,  86,  45],
       [ 81, 122, 101],
       [ 84, 130,  68]])

In [88]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr8=np.random.randint(0,10,size=(4,3))
arr9=np.random.randint(0,10,size=(4,3))

In [91]:
# Compare the two arrays with '>'
arr8>arr9


array([[ True,  True,  True],
       [False, False, False],
       [False,  True, False],
       [ True, False,  True]])

In [92]:
# Compare the two arrays with '>='
arr8>=arr9

array([[ True,  True,  True],
       [False, False, False],
       [ True,  True, False],
       [ True, False,  True]])

In [93]:
# Find which elements of the first array are greater than 7
arr8>7

array([[False,  True,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [94]:
# Which parts of each array are equal? (try using '==')
arr8==arr9

array([[False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False]])

In [97]:
# Sort one of the arrays you just created in ascending order
np.sort(arr8)

array([[6, 8, 8],
       [2, 2, 2],
       [3, 5, 7],
       [0, 7, 7]])

In [98]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr8)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [100]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr8)

1

In [103]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr8)

9

In [102]:
arr8

array([[6, 8, 8],
       [2, 2, 2],
       [3, 5, 7],
       [0, 7, 7]])

In [104]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr8, axis=1)

array([1, 0, 2, 1])

In [105]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr8, axis=0)

array([3, 1, 1])

In [106]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 0.17483301, -1.21685489,  1.04934739,  1.32510566,  0.73450106],
       [-0.95449726, -0.75117942, -1.13042805,  0.76997736,  1.26838952],
       [ 0.42448624,  0.94053558, -0.86764109,  0.14586185, -1.36987106]])

In [108]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])